[package]
name = "log_err"
version = "1.0.0"
authors = ["Kartavya Vashishtha <kartavya0703@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4.*"

[dev-dependencies]
simplelog = "^0.10.*"